version: "3"
services:
  db:
    image: postgres:latest
    container_name: local-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=local-db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - local-network

networks:
  local-network: